### ISSUE TITLE
Dat Manifest CSP controls

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#497]
Dats should host with the following default CSP:

```
default-src 'self'; img-src 'self' data: dat: blob:; object-src 'none';
```

The `content_security_policy` attribute in the manifest will then specify a set of additional policy flags, similar to:

```js
{
  "content_security_policy": {
    "script": {
      "unsafe_eval": true,
      "unsafe_inline": true,
      "domains": ["foo.com"],
      "sha256": [...]
   }
}
```

These policies will need to be subject to filtering. For instance, domains will only support `dat://`. Not all policies will be customizable, such as the `object-src` policy.

---

**Tasks**

 - [ ] Specify the full behavior
 - [ ] Implement the default CSP
 - [ ] Implement the manifest field
